# Generated by Django 4.0.2 on 2022-03-13 12:27

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LinksList',
            new_name='Link',
        ),
        migrations.RemoveField(
            model_name='person',
            name='links_list',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='users.category', verbose_name='Parent category'),
        ),
        migrations.AlterField(
            model_name='person',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Wallet address'),
        ),
    ]
