# Generated by Django 4.0.2 on 2022-03-20 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notions', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='creator',
        ),
    ]
