# Generated by Django 4.0.2 on 2022-03-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notions', '0003_remove_link_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='icon',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
