# Generated by Django 4.0.2 on 2022-03-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notions', '0006_remove_category_icon_link_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='icon',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default='', upload_to='media/'),
            preserve_default=False,
        ),
    ]
